#!/usr/bin/env bash

# I keep this command as an executable in my PATH instead of a simple alias
# because I use it in other scripts.

feh "$@" -B "white" -g "1280x720+360+180" -. -Z \
    --action1 'xclip -selection clipboard -t image/png -i %F' \
    --action2 'cp %F ~/documents/pictures/screenshots/'
# TODO: -- action3 'select dir and file name'
